/*
 * API MTIS - OpenAPI 3.0
 *
 * Practica grupal  de MTIS de la Universidad de Alicante 2022-2023.  _Esta documentacion esta escrita en el Swagger Editor y con OpenAPI 3.0_  `Autor: Nikita Polyanskiy, Serhii Vidernikov, Robert Kazaryan, Víctor Hernández Justamante y Ángel Tamame Pérez`
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;

namespace IO.Swagger.Models
{ 
    /// <summary>
    /// 
    /// </summary>
    [DataContract]
    public partial class Recurso : IEquatable<Recurso>
    { 
        /// <summary>
        /// Codigo de una sala
        /// </summary>
        /// <value>Codigo de una sala</value>
        [Required]

        [DataMember(Name="codigoSala")]
        public string CodigoSala { get; set; }

        /// <summary>
        /// Nombre de una sala
        /// </summary>
        /// <value>Nombre de una sala</value>
        [Required]

        [DataMember(Name="nombre")]
        public string Nombre { get; set; }

        /// <summary>
        /// Nivel de una sala
        /// </summary>
        /// <value>Nivel de una sala</value>
        [Required]

        [DataMember(Name="nivel")]
        public long? Nivel { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Recurso {\n");
            sb.Append("  CodigoSala: ").Append(CodigoSala).Append("\n");
            sb.Append("  Nombre: ").Append(Nombre).Append("\n");
            sb.Append("  Nivel: ").Append(Nivel).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (ReferenceEquals(null, obj)) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((Recurso)obj);
        }

        /// <summary>
        /// Returns true if Recurso instances are equal
        /// </summary>
        /// <param name="other">Instance of Recurso to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Recurso other)
        {
            if (ReferenceEquals(null, other)) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    CodigoSala == other.CodigoSala ||
                    CodigoSala != null &&
                    CodigoSala.Equals(other.CodigoSala)
                ) && 
                (
                    Nombre == other.Nombre ||
                    Nombre != null &&
                    Nombre.Equals(other.Nombre)
                ) && 
                (
                    Nivel == other.Nivel ||
                    Nivel != null &&
                    Nivel.Equals(other.Nivel)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (CodigoSala != null)
                    hashCode = hashCode * 59 + CodigoSala.GetHashCode();
                    if (Nombre != null)
                    hashCode = hashCode * 59 + Nombre.GetHashCode();
                    if (Nivel != null)
                    hashCode = hashCode * 59 + Nivel.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(Recurso left, Recurso right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(Recurso left, Recurso right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
