/*
 * API MTIS - OpenAPI 3.0
 *
 * Practica grupal  de MTIS de la Universidad de Alicante 2022-2023.  _Esta documentacion esta escrita en el Swagger Editor y con OpenAPI 3.0_  `Autor: Nikita Polyanskiy, Serhii Vidernikov, Robert Kazaryan, Víctor Hernández Justamante y Ángel Tamame Pérez`
 *
 * OpenAPI spec version: 1.0.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using Swashbuckle.AspNetCore.Annotations;
using Swashbuckle.AspNetCore.SwaggerGen;
using Newtonsoft.Json;
using System.ComponentModel.DataAnnotations;
using IO.Swagger.Attributes;

using Microsoft.AspNetCore.Authorization;
using IO.Swagger.Models;
using IO.Swagger.Utils;

namespace IO.Swagger.Controllers
{ 
    /// <summary>
    /// 
    /// </summary>
    [ApiController]
    public class SeguimientoApiController : ControllerBase
    { 
        /// <summary>
        /// Abrir acceso a un seguimiento para el cliente.
        /// </summary>
        /// <param name="id">ID del seguimiento</param>
        /// <response code="200">Success</response>
        /// <response code="400">Bad request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal error</response>
        [HttpPost]
        [Route("/VHJ1_1/MTIS/1.0.0/Seguimiento/{id}")]
        [ValidateModelState]
        [SwaggerOperation("OpenAccesoSeguimiento")]
        [SwaggerResponse(statusCode: 200, type: typeof(Response), description: "Success")]
        [SwaggerResponse(statusCode: 400, type: typeof(Response), description: "Bad request")]
        [SwaggerResponse(statusCode: 401, type: typeof(Response), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(Response), description: "Not found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Response), description: "Internal error")]
        public virtual IActionResult OpenAccesoSeguimiento([FromRoute][Required]string id)
        {
            Response response = new Response();
            string updateRowSQL = "UPDATE mtisteoria.seguimiento  SET acceso = '" + 1 + "' WHERE codigo = '" + id + "'";
            if (DBUtils.DbModif(updateRowSQL))
            {
                response.Status = "200";
                response.Message = "Se ha abierto el acceso al seguimiento";
                return Ok(response);
            }
            else
            {
                response.Status = "404";
                response.Message = "No se ha encontrado el seguimiento";
                return NotFound(response);

            }
        }

        /// <summary>
        /// Obtener información de seguimiento por ID
        /// </summary>
        /// <param name="id">ID del seguimiento a obtener</param>
        /// <param name="restKey">Api Key</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal error</response>
        [HttpGet]
        [Route("/VHJ1_1/MTIS/1.0.0/Seguimiento/{id}")]
        [ValidateModelState]
        [SwaggerOperation("SeguimientoIdGet")]
        [SwaggerResponse(statusCode: 200, type: typeof(Seguimiento), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(Response), description: "Bad request")]
        [SwaggerResponse(statusCode: 401, type: typeof(Response), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(Response), description: "Not found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Response), description: "Internal error")]
        public virtual IActionResult SeguimientoIdGet([FromRoute][Required]string id, [FromHeader]string restKey)
        { 
            var sql = "SELECT * FROM seguimiento WHERE codigo='"+id+"'";
            var result = DBUtils.DbGet(sql);
            if(result.Count != 0)
            {
                return StatusCode(200, result);
            }
            else
            {
                return StatusCode(400, JsonConvert.DeserializeObject("{\n  \"mensaje\" : \"No se han modificado filas\"\n}"));

            }
        }

        /// <summary>
        /// Crear un nuevo seguimiento
        /// </summary>
        /// <param name="body">Estructura para hacer peticiones</param>
        /// <param name="restKey">Api Key</param>
        /// <response code="201">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal error</response>
        [HttpPost]
        [Route("/VHJ1_1/MTIS/1.0.0/Seguimiento")]
        [ValidateModelState]
        [SwaggerOperation("SeguimientoPost")]
        [SwaggerResponse(statusCode: 200, type: typeof(Response), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(Response), description: "Bad request")]
        [SwaggerResponse(statusCode: 401, type: typeof(Response), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(Response), description: "Not found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Response), description: "Internal error")]
        public virtual IActionResult SeguimientoPost([FromBody]Seguimiento body, [FromHeader]string restKey)
        {

            Console.WriteLine("-----------------------------------");

            string insertRowSQL = "INSERT INTO mtisteoria.seguimiento (codigo, estado ,acceso, fk_paquete)" +
                    "VALUES('"+body.Identificador + "','procesando', 0, '"+body.envioId.ToString()+"')";
            Console.WriteLine(insertRowSQL);
            if (DBUtils.DbModif(insertRowSQL))
            {
                return StatusCode(200, JsonConvert.DeserializeObject("{\n  \"mensaje\" : \"Se ha creado el seguimiento\"\n}"));
            }
            else
            {
                return StatusCode(400, JsonConvert.DeserializeObject("{\n  \"mensaje\" : \"No se han modificado filas\"\n}"));
            }
        }

        /// <summary>
        /// Actualizar un seguimiento existente.
        /// </summary>
        /// <param name="body">Estructura para hacer peticiones</param>
        /// <param name="id">ID del seguimiento.</param>
        /// <response code="200">OK</response>
        /// <response code="400">Bad request</response>
        /// <response code="401">Unauthorized</response>
        /// <response code="404">Not found</response>
        /// <response code="500">Internal error</response>
        [HttpPut]
        [Route("/VHJ1_1/MTIS/1.0.0/Seguimiento/{id}")]
        [ValidateModelState]
        [SwaggerOperation("UpdateSeguimiento")]
        [SwaggerResponse(statusCode: 200, type: typeof(Seguimiento), description: "OK")]
        [SwaggerResponse(statusCode: 400, type: typeof(Response), description: "Bad request")]
        [SwaggerResponse(statusCode: 401, type: typeof(Response), description: "Unauthorized")]
        [SwaggerResponse(statusCode: 404, type: typeof(Response), description: "Not found")]
        [SwaggerResponse(statusCode: 500, type: typeof(Response), description: "Internal error")]
        public virtual IActionResult UpdateSeguimiento([FromBody]Seguimiento body, [FromRoute][Required]string id)
        {
            var accesoInt = 0;
            if (body.Acceso == true) {
                accesoInt = 1;
            }
            string updateRowSQL = "UPDATE mtisteoria.seguimiento SET acceso = '" + accesoInt + "', estado = '" + body.Estado + "' WHERE codigo = '" + id + "'";
            Console.WriteLine(updateRowSQL);

            if (DBUtils.DbModif(updateRowSQL))
            {
                return Ok("Se ha actualizado seguimiento");
                //return StatusCode(200, JsonConvert.DeserializeObject("{\n  \"mensaje\" : \"Se ha modificado el seguimiento\"\n}"));
            }
            else
            {
                return Ok("No se ha podido actualizar seguimiento");
                //return StatusCode(400, JsonConvert.DeserializeObject("{\n  \"mensaje\" : \"No se han modificado filas\"\n}"));
            }
        }
    }

}
